### PR TITLE
Added simple mvn github action.

### PR DESCRIPTION
**Pull request by aubelsb2**
Hey.

Given the recent issues. I have added a github action which will try compile (and possibly test) the code. This will catch any build failures on PR requests. Hopefully helping to ensure that all code gets into master at least builds. It can be made more sophisticated later if required. We can also add a -DskipTests if the tests aren't passing to simply verify compilation. 

(Converage is another option we could add.)

### CODE REVIEW

**Comment by aubelsb2** [comment]
This github action should fail (see https://github.com/aubelsb2/JSONata4Java/runs/3275922421?check_suite_focus=true) as per issue: https://github.com/IBM/JSONata4Java/issues/170 However it shold help prevent issues like that in the future.

**Comment by wnm3** [comment]
I apologize -- somehow I'd lost track of this request. I merged it today.

**Comment by wnm3** [comment]
Do you know where a private key is expected (e.g., in an environment variable or file location)? I don't think I can check that into github...

gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.314 s
[INFO] Finished at: 2022-05-20T11:55:30Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project JSONata4Java: Exit code: 2 -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by wnm3** [comment]
I've attempted to address this based on issue #196

**Comment by aubelsb2** [comment]
No problem. I am a contractor so I am unavailable for periods of time. I will look into the issue when I get some time to work on it. Sorry it's been a while. I will discuss later on the issue.

**Pull request merged**
