### PR TITLE
Function redesign

### PR DESCRIPTION
**Pull request by bluemel**
Here is a proposal for a redisign of the function implementations in JSONata4Java.
* idea is that every function implementation has the same frame
1) common context evaluation resulting in
   * JsonNode arg: first arument
   * int argumentCount:
   * boolean useContext
2) switch over argument count
* function implemenations re designed so far
   * AbsFunction
   * EachFunction
   * MatchFunction
   * FilterFunction
* A further idea is to convert the JUnit tests for function implementations in simple JUnitTests (neither parameterized nor part of the agnostic test suite). This will make error analysis and debugging maximally easy.
* Furthermore this pull request contains slight fixes on some of the redsigned functions concerning behaviour in edge cases (especially when an arument is null (no match)

### CODE REVIEW

**Comment by wnm3** [comment]
I am fine with your suggestion. I wouldn't delete any classes until you've gone through the functions... You can probably see where the method you wanted to delete was being called to understand the difference in approach.

I fully agree with cleaning up the JUnit testing to break things into more compartmental pieces. It should make it easier to identify where a particular test failed.  Note, I'd put different test data into a directory called testdata with the idea we could use those files in JUnit tests. For example, dataobject_i.json was for issue #237 though I hard coded the JSON in the BasicExpressionsTests (search on 237). It would take some time to determine which issue related to which file though.

**Comment by wnm3** [comment]
Argument counts get tricky because sometimes the first argument is the current data from the environment (what $ would point to) and other times it is passed explicitly to the function, so they need to be inferred rather than passed as a parameter. The MapFunction.json is a good example.

**Comment by wnm3** [comment]
Let me know if/when you'd like to merge this and create a new release.

**Comment by bluemel** [comment]
I think the branch is ready to be merged now with the fixes from you and me. Definitely we could close the latest issue after the new release (2
2.6?)

29.11.2022 17:13:46 Nathaniel Mills ***@***.***>:

**Comment by wnm3** [comment]
Already merged and released as version 2.2.5

**Pull request merged**
