### PR TITLE
Remove ANTLR generated sources from version control

### PR DESCRIPTION
**Pull request by bluemel**
This way we make a sharp distinction between real sources and Java source files generated by ANTLR and it is clear to everyone that we do not intend to add any manual work to the generated sources.
This will avoid unneccessary code changes in git as well as well as unneccessary conflicts and as well this is the default way to work with the antlr4-maven-plugin forseen by the ANTLR developers.
This is only for ease of development. For users of JSONata4Java nothing will change.

### CODE REVIEW

**Comment by bluemel** [comment]
Withdrawn other changes not directly related to this topic. Before all withdrawn any package renaming.

**Comment by wnm3** [comment]
Note: I'm going to make version 2.0 since we upped the version of Java to 11 to support Antlr 4.11.1

**Comment by bluemel** [comment]
Good Idea, Nat.According to the SemVer guidelines (see https://semver.org/) 2.0.0 is more correct anyway even if only tew particular JSONata mapping expressions might break with the new Version. And Java 1.8 wont be probably supported anymore by Oracle.BR MartinAm 20.09.22, 17:25 schrieb Nathaniel Mills ***@***.***>:

   
  Note: I'm going to make version 2.0 since we upped the version of Java to 11 to support Antlr 4.11.1

**Comment by wnm3** [comment]
I just pushed to Maven Central -- it will take a few hours before it shows up. Thanks again for your persistence and great work to improve JSONata4Java!

**Pull request merged**
